### ISSUE TITLE
Crash after a tracked entity is removed

### ISSUE THREAD

**Issue by Bilka2** [justarandomgeek/nixie-tubes#15]
A user of my [NewGame+](https://github.com/Bilka2/NewGamePlus) mod [reported](https://mods.factorio.com/mods/Bilka/NewGamePlus/discussion/21171) that the game crashed due to your mod after generating the new world:

>5548.346 Script @NewGamePlus/control.lua:7: New game plus has been generated
5548.739 Error MainLoop.cpp:940: Exception at tick 20313452: Error while running event nixie-tubes::on_tick (ID 0)
nixie-tubes/control.lua:302: attempt to call global 'onRemoveEntity' (a nil value)

The initial error here is that the function that is called is a local function which is below the line that calls it, so it cannot be found. But even with that, there is still an issue: Your mod only checks if the entity it's trying to update is invalid, not if it even exists (which it doesn't, my mod deletes everything on nauvis). Since it's invalid, onRemoveEntity is called but does nothing as far as I can see.

**Comment by justarandomgeek** [comment]
onRemoveEntity requires a still-valid entity to do anything useful, as it's mostly about making sure my various tick-smeared loops don't have hiccups on removal. It actually has nothing to do in the case of an invalid entity, so really that call from onTickController should probably just be removed. However, onRemoveEntity *itself* being nil, as indicated by this error, is very strange, as that should only be possible before events are running - after that, all the functions are present in that file's local scope, which is why it works fine for the rest of the world.

So the actual problem is that somehow my onRemoveEntity function didn't get defined in time - my money is on modified mod files.

I'll make an update soon to clean up this and some other now-useless leftovers I've spotted just now, and will test with your mod then.
